### PR TITLE
Add linux solution, move windows code to windows

### PR DESCRIPTION
**Pull request by strega-nil**
subdirectory

### CODE REVIEW

**Comment by strega-nil** [comment]
I gave a ... creative ... solution, to get around the "no assembly" restriction.

**Comment by vi** [comment]
Looks arch-specific and a bit like a cheat.

Expecting to see (someday) the Linux solution that is as readable and portable as the Windows one.

**Comment by strega-nil** [comment]
@vi more fun that way.

**Comment by strega-nil** [comment]
@vi the issue is that Windows exports symbols to call outside the c standard library, while Linux does not. You must link the c standard library in order to call write, if you don't want to call the syscalls yourself.

**Comment by vi** [comment]
I expect it to just call from standard library a function to do unbuffered write of specified byte buffer to specified OS file descriptor and Rust to agressively remove&inline until the whole program is just something like `syscall(SYS_write, 1, "hello, world", 12)`.

So for each byte in `.text` or `.data` you can say why it's needed for "hello world" (othersize it should be dropped).

The undelying reason for this challenge is to improve rustc, isn't it?

**Comment by strega-nil** [comment]
@vi it's now an actual attempt.

**Comment by vi** [comment]
@ubsan, syscall.rs fix should be upstream and the example should refer to crates.io instead of a submodule.

**Comment by strega-nil** [comment]
@vi syscall.rs is broken, currently, and it hasn't been updated in 7 months. Also, it needs project specific tweaks (#![no_core]).

**Comment by vi** [comment]
How much load does libcore add? Why isn't it get optimized away to zero if nothing from it is really used?

I except libcore to contain much things that should not produce any machine code at all.

**Comment by strega-nil** [comment]
@vi I don't know. Check it out, see where it gets us, and pull request.

**Pull request merged**
